language: php

php:
  - '7.0' 

before_script: 
  composer self-update
  composer require "squizlabs/php_codesniffer=*"
  composer create-project wp-coding-standards/wpcs:dev-master --no-dev

script:
  vendor/bin/phpcs --config-set installed_paths wpcs
  vendor/bin/phpcs -i
  vendor/bin/phpcs --standard=WordPress test.php


